'use strict';

var translationsEN = {
  "NOIMAGE" : "No Image",
  "CATEGORY" : "Category: ", 
  "NAME" : "Name: {{ displayvalue }}",
  "ADDRESS" : "Address: {{ displayvalue }}",
  "PHONENUM" : "Phone Number: {{ displayvalue }}",
  "FAXNUM" : "Fax Number: {{ displayvalue }}",
  "URL" : "Url: ",
  "ATTRACTION" : "Attractions",
  "SHOPPING" : "Shopping/Dining",
  "HOTEL" : "Hotels",
  "OTHERVENUE" : "Other Venues",
  "BRAND" : "Hong Kong",
  "NUM" : "Count: {{result_count}}",
  "SEARCH" : "Search: ",
  "W0" : "Facilities inaccessible to wheelchair users", 
  "W2" : "Facilities accessible to wheelchair users and meeting local design standard",
  "W1" : "Facilities accessible to wheelchair users but not up to local design standard",
  "H" : "Facilities available for hearing impaired persons",
  "V" : "Facilities available for visually impaired persons",
  "P1" : "Parking facilities available",
  "P2" : "Car park with reserved parking space for disabled drivers", 
  "L" : "Locked",
  "N/A" : "Facilities unavailable",
  "main-entrance" : "Services at main entrance",
  "information-counter" : "Services at Information Counter",
  "ticketing-office" : "Services at ticketing office",
  "exhibition-area" : "Services at exhibition area", 
  "lift-area" : "Services at lift area",
  "public-toilet" : "Services at public toilet",
  "public-telephone" : "Services at public telephone",
  "wheelchair-seating" : "Services at wheelchair seating",
  "car-park" : "Services at car park",
  "corridor" : "Services at corridor",
  "passages" : "Services at passages", 
  "drop-off" : "Services at drop off",
  "lobby" : "Services at Lobby", 
  "reception" : "Services at reception",
  "other-facilities" : "Services at other facilities",
  "guest-room" : "Services at guest rooms",
  "guest-room-toilet" : "Services at toilet in guest room",
  "chapels" : "Services at Chapels", 
  "church" : "Services at church",
  "language" : "Services about language",
  "temples-main" : "Services at temples (main)", 
  "temple-other" : "Services at temples (other facilities)",
  "exhibition-hall" : "Services at Exhibition Hall",
  "FIRST" : "First",
  "PREVIOUS" : "Previous", 
  "NEXT" : "Next",
  "LAST" : "Last",
  "LOCNAME_HINT" : "location name...",
  "ADDRESSNAME_HINT" : "address name...",
  "PHONENUM_HINT" : "phone number...",
  "temples" : "Temples",
  "market" : "Market",
  "museum" : "Museum",
  "scenic-spots" : "Scenic Spots",
  "theme-parks" : "Theme Parks",
  "arts-and-performance-centres" : "Art and Performance Centres",
  "hotel" : "Hotel", 
  "shopping-malls" : "Shopping Malls",
  "food-courts" : "Food Courts",
  "hong-kong-convention-and-exhibition-centres" : "Exhibition Centres",
  "computer-centre" : "Computer Centre",
  "church1" : "Church",
  "temples_button" : "Temples({{elementCount}})",
  "market_button" : "Market({{elementCount}})",
  "museum_button" : "Museum({{elementCount}})",
  "scenic-spots_button" : "Scenic Spots({{elementCount}})",
  "theme-parks_button" : "Theme Parks({{elementCount}})",
  "arts-and-performance-centres_button" : "Art and Performance Centres({{elementCount}})",
  "hotel_button" : "Hotel({{elementCount}})", 
  "shopping-malls_button" : "Shopping Malls({{elementCount}})",
  "food-courts_button" : "Food Courts({{elementCount}})",
  "hong-kong-convention-and-exhibition-centres_button" : "Exhibition Centres({{elementCount}})",
  "computer-centre_button" : "Computer Centre({{elementCount}})",
  "church1_button" : "Church({{elementCount}})",
  "EN_LANG" : "English",
  "TC_LANG" : "Traditional Chinese",
  "CHANGE_LANG" : "Change Language: ",
  "SHOW_MAP_ADDRESS" : "Show address in map",
  "CLOSE" : "Close",
  "SHOW_ADDRESS" : "Show Address: ",
  "OPEN_DIALOG" : "Show Address",
  "VERSION" : "Version: ",
  "AUTHOR" : "Author: ",
  "MAP" : "Map",
  DIALOGS_ERROR: "Error",
  DIALOGS_ERROR_MSG: "An unknown error has occurred.",
  DIALOGS_CLOSE: "Close",
  DIALOGS_PLEASE_WAIT: "Please Wait",
  DIALOGS_PLEASE_WAIT_ELIPS: "Please Wait...",
  DIALOGS_PLEASE_WAIT_MSG: "Waiting on operation to complete.",
  DIALOGS_PERCENT_COMPLETE: "% Complete",
  DIALOGS_NOTIFICATION: "Notification",
  DIALOGS_NOTIFICATION_MSG: "Unknown application notification.",
  DIALOGS_CONFIRMATION: "Confirmation",
  DIALOGS_CONFIRMATION_MSG: "Confirmation required.",
  DIALOGS_OK: "OK",
  DIALOGS_YES: "Yes",
  DIALOGS_NO: "No", 
  MARKER_HEADER : "Visible: {{num_marker}} marker(s),  {{total_markers}} in total",
  LAT_LNG : "Lat/Lng: {{lat}}, {{ lng }}",
  CHOOSE_CATEGORY : "Choose category:",
  LINKS : "Related Links",
  GEOLOCATION : "Accessible Location Map",
  APP_TITLE:  "Accessible facilities in Hong Kong"
}

var translationsZHHK = {
  "NOIMAGE" : "沒有圖片",
  "CATEGORY" : "類別： ", 
  "NAME" : "名稱： {{ displayvalue }}",
  "ADDRESS" : "地址： {{ displayvalue }}",
  "PHONENUM" : "電話號碼： {{ displayvalue }}",
  FAXNUM : "傳真號碼： {{ displayvalue }}",
  URL : "網址： ",
  ATTRACTION : "觀光景點",
  SHOPPING : "購物及餐飲",
  HOTEL : "酒店",
  OTHERVENUE : "其他場所",
  BRAND : "香港",
  NUM : "數目: {{result_count}}",
  SEARCH : "搜索：",
  W0 : "設施不適合輪椅使用者", 
  W2 : "設施符合本地通用設計標準，適合輪椅使用者",
  W1 : "設施不完全符合本地通用設計標準，但輪椅使用者亦能使用",
  H : "有為聽覺受損人士而設之設施",
  V : "有為視覺受損人士而設之設施",
  P1 : "設有停車場，但沒有殘疾人士車位",
  P2 : "設有停車場，並設有殘疾人士車位", 
  L : "設施被上鎖",
  "N/A" : "沒有該種設施或不需用該種設施",
  "main-entrance" : "主要入口",
  "information-counter" : "詢問處",
  "ticketing-office" : "售票處",
  "exhibition-area" : "展覽館", 
  "lift-area" : "升降機",
  "public-toilet" : "公共洗手間",
  "public-telephone" : "公共電話",
  "wheelchair-seating" : "輪椅使用者座位",
  "car-park" : "停車場",
  "corridor" : "走廊",
  "passages" : "通道", 
  "drop-off" : "上落處",
  "lobby" : "大堂", 
  "reception" : "接待處",
  "other-facilities" : "其他設施",
  "guest-room" : "客房",
  "guest-room-toilet" : "客房洗手間",
  "chapels" : "小教堂", 
  "church" : "教堂",
  "language" : "語言相關服務",
  "temples-main" : "主要寺廟", 
  "temple-other" : "寺廟",
  "exhibition-hall" : "展覽大廳",
  FIRST : "第一頁",
  PREVIOUS : "上一頁", 
  NEXT : "下一頁",
  LAST : "最後一頁",
  LOCNAME_HINT : "地點...",
  ADDRESSNAME_HINT : "地址...",
  PHONENUM_HINT : "電話號碼...",
  temples : "寺廟",
  market : "市場",
  museum : "博物館",
  "scenic-spots" : "名勝",
  "theme-parks" : "主題公園",
  "arts-and-performance-centres" : "藝術和表演中心",
  "hotel" : "酒店", 
  "shopping-malls" : "商場",
  "food-courts" : "美食廣場",
  "hong-kong-convention-and-exhibition-centres" : "會議及展覽中心",
  "computer-centre" : "電腦商場",
  "church1" : "教堂",
  temples_button : "寺廟({{elementCount}})",
  market_button : "市場({{elementCount}})",
  museum_button : "博物館({{elementCount}})",
  "scenic-spots_button" : "名勝({{elementCount}})",
  "theme-parks_button" : "主題公園({{elementCount}})",
  "arts-and-performance-centres_button" : "藝術和表演中心({{elementCount}})",
  "hotel_button" : "酒店({{elementCount}})", 
  "shopping-malls_button" : "商場({{elementCount}})",
  "food-courts_button" : "美食廣場({{elementCount}})",
  "hong-kong-convention-and-exhibition-centres_button" : "會議及展覽中心({{elementCount}})",
  "computer-centre_button" : "電腦商場({{elementCount}})",
  "church1_button" : "教堂({{elementCount}})",
  EN_LANG : "英文",
  TC_LANG : "繁體中文",
  CHANGE_LANG : "語言：",
  "SHOW_MAP_ADDRESS" : "顯示地址",
  "CLOSE" : "關閉",
  "SHOW_ADDRESS" : "地址： ",
  "OPEN_DIALOG" : "顯示地址",
  "VERSION" : "版本： ",
  "AUTHOR" : "作者： ",
  "MAP" : "地圖",
  DIALOGS_ERROR: "錯誤",
  DIALOGS_ERROR_MSG: "發生不明的錯誤。",
  DIALOGS_CLOSE: "關閉",
  DIALOGS_PLEASE_WAIT: "請稍候",
  DIALOGS_PLEASE_WAIT_ELIPS: "請稍候...",
  DIALOGS_PLEASE_WAIT_MSG: "等待操作完成。",
  DIALOGS_PERCENT_COMPLETE: "% 完成",
  DIALOGS_NOTIFICATION: "通知",
  DIALOGS_NOTIFICATION_MSG: "未知應用程序的通知。",
  DIALOGS_CONFIRMATION: "確認",
  DIALOGS_CONFIRMATION_MSG: "需要確認。",
  DIALOGS_OK: "確定",
  DIALOGS_YES: "是",
  DIALOGS_NO: "否",
  MARKER_HEADER : "載入 {{num_marker}} 個座標,  共計 {{total_markers}} 個座標",
  LAT_LNG : "經緯度: {{lat}}, {{ lng }}",
  CHOOSE_CATEGORY : "選擇類別：",
  LINKS : "相關連結",
  GEOLOCATION : "無障礙場所位置圖",
  APP_TITLE:  "香港無障礙設施"
};

// Declare app level module which depends on filters, and services
var myApp = angular.module('hkAccessibleApp', [
  'hkAccessibleServices',
  'hkAccessibleFilters',
  'hkDirectives',
  'hkAccessibleControllers',
  'linkController',
  'accessibleController',
  'mapController',
  'hkRouter',
  'pascalprecht.translate',
  'ui.map',
  'ui.event',
  'ui.bootstrap',
  'multi-select',
  'dialogs.main',
  'dialogs.controllers',
  'angular-underscore'
]);

myApp
.config(['$translateProvider', function($translateProvider) {
    $translateProvider.translations('zh_hk', translationsZHHK)
      .translations('en', translationsEN);
    $translateProvider.preferredLanguage('zh_hk');
    $translateProvider.fallbackLanguage('zh_hk');
    $translateProvider.useMissingTranslationHandlerLog();
}]);

